# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ai-translation-app"
client_id = "c354998cfc2751d121b7cc1a8cbdbdb1"
application_url = "https://unauthorized-s-trading-functions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://unauthorized-s-trading-functions.trycloudflare.com/auth/callback",
  "https://unauthorized-s-trading-functions.trycloudflare.com/auth/shopify/callback",
  "https://unauthorized-s-trading-functions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "translationappdev.myshopify.com"
