# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "translationappmf"
client_id = "138e1cce5b96d7573dbf5afcb607f166"
application_url = "https://tie-frost-lamp-feeding.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, write_orders, read_draft_orders, write_draft_orders, read_customers, write_customers, read_checkouts, write_checkouts, read_reports, write_reports, read_fulfillments, write_fulfillments, read_shipping, write_shipping, read_all_orders"

[auth]
redirect_urls = [
  "https://tie-frost-lamp-feeding.trycloudflare.com/auth/callback",
  "https://tie-frost-lamp-feeding.trycloudflare.com/auth/shopify/callback",
  "https://tie-frost-lamp-feeding.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "translationapp.myshopify.com"
