# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "translationapp"
client_id = "bab053ea934eaff6d7b9f52a53e875d6"
application_url = "https://images-setup-wifi-treating.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://images-setup-wifi-treating.trycloudflare.com/auth/callback",
  "https://images-setup-wifi-treating.trycloudflare.com/auth/shopify/callback",
  "https://images-setup-wifi-treating.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingtranslationapp.myshopify.com"
