# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Translationtest"
client_id = "beaf487c4502255b8f9821fc5a568f79"
application_url = "https://translation-app-zeta.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true
scopes="read_products,write_products,read_content, read_online_store_pages"

[auth]
redirect_urls = [ "https://translation-app-zeta.vercel.app/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
