# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "translationapp"
client_id = "ede35f373151f4f1f9090e46213d40f8"
application_url = "https://centers-sie-spider-titanium.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://centers-sie-spider-titanium.trycloudflare.com/auth/callback",
  "https://centers-sie-spider-titanium.trycloudflare.com/auth/shopify/callback",
  "https://centers-sie-spider-titanium.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "translationapp.myshopify.com"
